version: '3.8'

services:
  user_database:
    image: postgres:16.2
    container_name: user_database
    restart: always
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ../build:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:${DB_PORT}

  main_service:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: build/Dockerfile
    env_file:
      - .env
    command:
      [
        "./main",
        "--config_path",
        "build/config.yaml",
        "--port",
        "$MAIN_SERVICE_PORT"
      ]
    container_name: main_service
    depends_on:
      - user_database
    ports:
      - ${MAIN_SERVICE_PORT}:${MAIN_SERVICE_PORT}
