@startuml Context

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Social Network Context Diagram

Person(user, "User", "Social network user")

System_Boundary(socialNetwork, "Social network") {
    System(userService, "User service", "")

    System_Ext(statisticsService, "Statistics service", "Counts likes, views")
    System_Ext(contentService, "Content service", "Manages posts, comments")
}

Rel(userService, statisticsService, "")
Rel(userService, contentService, "")
Rel(user, userService, "API, Registration, Authentication")

@enduml