// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: stat_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTopPostsRequest_SortBy int32

const (
	GetTopPostsRequest_VIEWS GetTopPostsRequest_SortBy = 0
	GetTopPostsRequest_LIKES GetTopPostsRequest_SortBy = 1
)

// Enum value maps for GetTopPostsRequest_SortBy.
var (
	GetTopPostsRequest_SortBy_name = map[int32]string{
		0: "VIEWS",
		1: "LIKES",
	}
	GetTopPostsRequest_SortBy_value = map[string]int32{
		"VIEWS": 0,
		"LIKES": 1,
	}
)

func (x GetTopPostsRequest_SortBy) Enum() *GetTopPostsRequest_SortBy {
	p := new(GetTopPostsRequest_SortBy)
	*p = x
	return p
}

func (x GetTopPostsRequest_SortBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetTopPostsRequest_SortBy) Descriptor() protoreflect.EnumDescriptor {
	return file_stat_service_proto_enumTypes[0].Descriptor()
}

func (GetTopPostsRequest_SortBy) Type() protoreflect.EnumType {
	return &file_stat_service_proto_enumTypes[0]
}

func (x GetTopPostsRequest_SortBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetTopPostsRequest_SortBy.Descriptor instead.
func (GetTopPostsRequest_SortBy) EnumDescriptor() ([]byte, []int) {
	return file_stat_service_proto_rawDescGZIP(), []int{2, 0}
}

type GetViewsLikesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetViewsLikesRequest) Reset() {
	*x = GetViewsLikesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetViewsLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewsLikesRequest) ProtoMessage() {}

func (x *GetViewsLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stat_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewsLikesRequest.ProtoReflect.Descriptor instead.
func (*GetViewsLikesRequest) Descriptor() ([]byte, []int) {
	return file_stat_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetViewsLikesRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetViewsLikesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Views int64 `protobuf:"varint,1,opt,name=views,proto3" json:"views,omitempty"`
	Likes int64 `protobuf:"varint,2,opt,name=likes,proto3" json:"likes,omitempty"`
}

func (x *GetViewsLikesResponse) Reset() {
	*x = GetViewsLikesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetViewsLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewsLikesResponse) ProtoMessage() {}

func (x *GetViewsLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stat_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewsLikesResponse.ProtoReflect.Descriptor instead.
func (*GetViewsLikesResponse) Descriptor() ([]byte, []int) {
	return file_stat_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetViewsLikesResponse) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *GetViewsLikesResponse) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

type GetTopPostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SortBy GetTopPostsRequest_SortBy `protobuf:"varint,1,opt,name=sort_by,json=sortBy,proto3,enum=stats.GetTopPostsRequest_SortBy" json:"sort_by,omitempty"`
}

func (x *GetTopPostsRequest) Reset() {
	*x = GetTopPostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPostsRequest) ProtoMessage() {}

func (x *GetTopPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stat_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPostsRequest.ProtoReflect.Descriptor instead.
func (*GetTopPostsRequest) Descriptor() ([]byte, []int) {
	return file_stat_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopPostsRequest) GetSortBy() GetTopPostsRequest_SortBy {
	if x != nil {
		return x.SortBy
	}
	return GetTopPostsRequest_VIEWS
}

type GetTopPostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Posts []*GetTopPostsResponse_Post `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
}

func (x *GetTopPostsResponse) Reset() {
	*x = GetTopPostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPostsResponse) ProtoMessage() {}

func (x *GetTopPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stat_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPostsResponse.ProtoReflect.Descriptor instead.
func (*GetTopPostsResponse) Descriptor() ([]byte, []int) {
	return file_stat_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTopPostsResponse) GetPosts() []*GetTopPostsResponse_Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type GetTopUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopUsers []*GetTopUsersResponse_UserStat `protobuf:"bytes,1,rep,name=top_users,json=topUsers,proto3" json:"top_users,omitempty"`
}

func (x *GetTopUsersResponse) Reset() {
	*x = GetTopUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUsersResponse) ProtoMessage() {}

func (x *GetTopUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stat_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUsersResponse.ProtoReflect.Descriptor instead.
func (*GetTopUsersResponse) Descriptor() ([]byte, []int) {
	return file_stat_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTopUsersResponse) GetTopUsers() []*GetTopUsersResponse_UserStat {
	if x != nil {
		return x.TopUsers
	}
	return nil
}

type GetTopPostsResponse_Post struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostAuthor int32  `protobuf:"varint,2,opt,name=post_author,json=postAuthor,proto3" json:"post_author,omitempty"`
	Views      int64  `protobuf:"varint,3,opt,name=views,proto3" json:"views,omitempty"`
	Likes      int64  `protobuf:"varint,4,opt,name=likes,proto3" json:"likes,omitempty"`
}

func (x *GetTopPostsResponse_Post) Reset() {
	*x = GetTopPostsResponse_Post{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopPostsResponse_Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPostsResponse_Post) ProtoMessage() {}

func (x *GetTopPostsResponse_Post) ProtoReflect() protoreflect.Message {
	mi := &file_stat_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPostsResponse_Post.ProtoReflect.Descriptor instead.
func (*GetTopPostsResponse_Post) Descriptor() ([]byte, []int) {
	return file_stat_service_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetTopPostsResponse_Post) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTopPostsResponse_Post) GetPostAuthor() int32 {
	if x != nil {
		return x.PostAuthor
	}
	return 0
}

func (x *GetTopPostsResponse_Post) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *GetTopPostsResponse_Post) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

type GetTopUsersResponse_UserStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Likes  int64 `protobuf:"varint,2,opt,name=likes,proto3" json:"likes,omitempty"`
}

func (x *GetTopUsersResponse_UserStat) Reset() {
	*x = GetTopUsersResponse_UserStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopUsersResponse_UserStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUsersResponse_UserStat) ProtoMessage() {}

func (x *GetTopUsersResponse_UserStat) ProtoReflect() protoreflect.Message {
	mi := &file_stat_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUsersResponse_UserStat.ProtoReflect.Descriptor instead.
func (*GetTopUsersResponse_UserStat) Descriptor() ([]byte, []int) {
	return file_stat_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetTopUsersResponse_UserStat) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTopUsersResponse_UserStat) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

var File_stat_service_proto protoreflect.FileDescriptor

var file_stat_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x56,
	0x69, 0x65, 0x77, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x43, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x4c, 0x69, 0x6b, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x65,
	0x77, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x6c, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x6f, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x50,
	0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x07, 0x73,
	0x6f, 0x72, 0x74, 0x5f, 0x62, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x52, 0x06,
	0x73, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x22, 0x1e, 0x0a, 0x06, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79,
	0x12, 0x09, 0x0a, 0x05, 0x56, 0x49, 0x45, 0x57, 0x53, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c,
	0x49, 0x4b, 0x45, 0x53, 0x10, 0x01, 0x22, 0xb1, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f,
	0x70, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35,
	0x0a, 0x05, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x05,
	0x70, 0x6f, 0x73, 0x74, 0x73, 0x1a, 0x63, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76,
	0x69, 0x65, 0x77, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x74, 0x6f, 0x70, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x52, 0x08, 0x74, 0x6f, 0x70, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x1a, 0x39, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x32,
	0xe2, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x73,
	0x12, 0x1b, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77,
	0x73, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x73, 0x4c, 0x69,
	0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x6f, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x41, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stat_service_proto_rawDescOnce sync.Once
	file_stat_service_proto_rawDescData = file_stat_service_proto_rawDesc
)

func file_stat_service_proto_rawDescGZIP() []byte {
	file_stat_service_proto_rawDescOnce.Do(func() {
		file_stat_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_stat_service_proto_rawDescData)
	})
	return file_stat_service_proto_rawDescData
}

var file_stat_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stat_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_stat_service_proto_goTypes = []interface{}{
	(GetTopPostsRequest_SortBy)(0),       // 0: stats.GetTopPostsRequest.SortBy
	(*GetViewsLikesRequest)(nil),         // 1: stats.GetViewsLikesRequest
	(*GetViewsLikesResponse)(nil),        // 2: stats.GetViewsLikesResponse
	(*GetTopPostsRequest)(nil),           // 3: stats.GetTopPostsRequest
	(*GetTopPostsResponse)(nil),          // 4: stats.GetTopPostsResponse
	(*GetTopUsersResponse)(nil),          // 5: stats.GetTopUsersResponse
	(*GetTopPostsResponse_Post)(nil),     // 6: stats.GetTopPostsResponse.Post
	(*GetTopUsersResponse_UserStat)(nil), // 7: stats.GetTopUsersResponse.UserStat
	(*emptypb.Empty)(nil),                // 8: google.protobuf.Empty
}
var file_stat_service_proto_depIdxs = []int32{
	0, // 0: stats.GetTopPostsRequest.sort_by:type_name -> stats.GetTopPostsRequest.SortBy
	6, // 1: stats.GetTopPostsResponse.posts:type_name -> stats.GetTopPostsResponse.Post
	7, // 2: stats.GetTopUsersResponse.top_users:type_name -> stats.GetTopUsersResponse.UserStat
	1, // 3: stats.StatService.GetViewsLikes:input_type -> stats.GetViewsLikesRequest
	3, // 4: stats.StatService.GetTopPosts:input_type -> stats.GetTopPostsRequest
	8, // 5: stats.StatService.GetTopUsers:input_type -> google.protobuf.Empty
	2, // 6: stats.StatService.GetViewsLikes:output_type -> stats.GetViewsLikesResponse
	4, // 7: stats.StatService.GetTopPosts:output_type -> stats.GetTopPostsResponse
	5, // 8: stats.StatService.GetTopUsers:output_type -> stats.GetTopUsersResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_stat_service_proto_init() }
func file_stat_service_proto_init() {
	if File_stat_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stat_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetViewsLikesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stat_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetViewsLikesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stat_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopPostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stat_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopPostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stat_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stat_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopPostsResponse_Post); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stat_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopUsersResponse_UserStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stat_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stat_service_proto_goTypes,
		DependencyIndexes: file_stat_service_proto_depIdxs,
		EnumInfos:         file_stat_service_proto_enumTypes,
		MessageInfos:      file_stat_service_proto_msgTypes,
	}.Build()
	File_stat_service_proto = out.File
	file_stat_service_proto_rawDesc = nil
	file_stat_service_proto_goTypes = nil
	file_stat_service_proto_depIdxs = nil
}
