openapi: 3.0.0
info:
  title: Main Service API
  version: 1.0.0
  description: API for user authentication and authorization

paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          $ref: '#/components/responses/AuthSuccess'
        '409':
          description: User already exists

  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          $ref: '#/components/responses/AuthSuccess'
        '401':
          description: Incorrect login/password
          

  /update:
    put:
      summary: Update user data
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                date_of_birth:
                  type: string
                  format: date
                email:
                  type: string
                  format: email
                phone_number:
                  type: string
      responses:
        '200':
          description: User data updated successfully
        '401':
          description: Unauthorized, invalid or expired token

components:
  responses:
    AuthSuccess:
      description: Successful authentication
      content:
        application/json:
          schema:
            type: object
            properties:
              token:
                type: string
              expiration_date:
                type: string
                format: date-time

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

