version: '3.8'

services:
  user_database:
    image: postgres:16.2
    container_name: user_database
    restart: always
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB}
      POSTGRES_USER: ${USER_DB_USER}
    volumes:
      - ./user_service/build:/docker-entrypoint-initdb.d
    ports:
      - ${USER_DB_PORT}:5432

  user_service:
    restart: unless-stopped
    build:
      context: ./user_service/
      dockerfile: build/Dockerfile
    env_file:
      - .env
    command:
      [
        "./main",
        "--config_path",
        "build/config.yaml",
        "--port",
        "$USER_SERVICE_PORT"
      ]
    container_name: user_service
    depends_on:
      - user_database
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
  content_database:
    image: postgres:16.2
    container_name: content_database
    restart: always
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: ${CONTENT_DB_PASSWORD}
      POSTGRES_DB: ${CONTENT_DB}
      POSTGRES_USER: ${CONTENT_DB_USER}
    volumes:
      - ./content_serive/build:/docker-entrypoint-initdb.d
    ports:
      - ${CONTENT_DB_PORT}:5432

  content_service:
    restart: unless-stopped
    build:
      context: ./content_service/
      dockerfile: build/Dockerfile
    env_file:
      - .env
    command: [ "./main", "--port", "$CONTENT_SERVICE_PORT" ]
    container_name: content_service
    depends_on:
      - content_database
      - user_service
    ports:
      - ${CONTENT_SERVICE_PORT}:${CONTENT_SERVICE_PORT}
