name: Integration tests

on:
  [push, pull_request]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build Docker images
        run: |
          cd src 
          docker-compose build

      - name: Start Docker Compose services
        run: |
          cd src
          docker-compose up -d

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
  
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
  
      - name: Run Python script
        run: |
          python test/test.py

      - name: Run unit tests
        run: |
          docker exec user_service /bin/bash -c "go test -v ./..."
          docker exec content_service /bin/bash -c "go test -v ./..."
          docker exec stat_service /bin/bash -c "go test -v ./..."

      - name: Stop Docker Compose services
        run: |
          cd src
          docker-compose down


